[package]
name = "fabric"
version = "0.1.0"
edition = "2018"

[[example]]
name = "edu"
path = "examples/edu/src/main.rs"
crate-type = ["bin"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
