[package]
name = "ca_client"
version = "0.1.0"
edition = "2018"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[dependencies]
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
fabric = { path = "../../" }
